### ISSUE TITLE
全局设置没有覆盖所有组件

### ISSUE THREAD

**Issue by zhangtaoqd** [DevCloudFE/ng-devui#103]
全局设置没有覆盖所有组件

**Comment by ZOUJIELynn** [comment]
当前提供的showAnimation涉及的组件都有，主要根据组件是否存在此功能做设置

**Comment by ZOUJIELynn** [comment]
> 全局设置没有覆盖所有组件

当前提供的showAnimation涉及的组件都有，主要根据组件是否存在此功能做设置
