### ISSUE TITLE
异步创建的组件应当在 `entryComponents` 中声明

### ISSUE THREAD

**Issue by Xie-Jay** [DevCloudFE/ng-devui#109]
```
      this.stepRef = this.overlayContainerRef.createComponent(
        this.componentFactoryResolver.resolveComponentFactory(StepsGuideComponent)
      );
```

**Comment by ZOUJIELynn** [comment]
https://update.angular.io/?l=3&v=9.0-11.0
Angular升级指南中有提到IVY与运行是不再需要entryComponents，我们升级后做了测试，请问下是组件有什么表现异常么

**Comment by Xie-Jay** [comment]
> https://update.angular.io/?l=3&v=9.0-11.0
> Angular升级指南中有提到IVY与运行时不再需要entryComponents，我们升级后做了测试，请问下是组件有什么表现异常么

@ZOUJIELynn stackblitz 测试中, 如果没有 `entryComponents`, 会出现以下错误,
![image](https://user-images.githubusercontent.com/64340763/116660146-3226ff00-a9c5-11eb-842f-53a0c1ea7bc3.png)

**Comment by ZOUJIELynn** [comment]
> > https://update.angular.io/?l=3&v=9.0-11.0
> > Angular升级指南中有提到IVY与运行时不再需要entryComponents，我们升级后做了测试，请问下是组件有什么表现异常么
> 
> @ZOUJIELynn stackblitz 测试中, 如果没有 `entryComponents`, 会出现以下错误,
> ![image](https://user-images.githubusercontent.com/64340763/116660146-3226ff00-a9c5-11eb-842f-53a0c1ea7bc3.png)

stackblitz中angular的版本号是^11.0.0么

**Comment by ZOUJIELynn** [comment]
> > > https://update.angular.io/?l=3&v=9.0-11.0
> > > Angular升级指南中有提到IVY与运行时不再需要entryComponents，我们升级后做了测试，请问下是组件有什么表现异常么
> > 
> > 
> > @ZOUJIELynn stackblitz 测试中, 如果没有 `entryComponents`, 会出现以下错误,
> > ![image](https://user-images.githubusercontent.com/64340763/116660146-3226ff00-a9c5-11eb-842f-53a0c1ea7bc3.png)
> 
> stackblitz中angular的版本号是^11.0.0么

在我们提供的stackblitz的ng11项目中复现了，我看看怎么处理这个问题哈

**Comment by ZOUJIELynn** [comment]
> > https://update.angular.io/?l=3&v=9.0-11.0
> > Angular升级指南中有提到IVY与运行时不再需要entryComponents，我们升级后做了测试，请问下是组件有什么表现异常么
> 
> @ZOUJIELynn stackblitz 测试中, 如果没有 `entryComponents`, 会出现以下错误,
> ![image](https://user-images.githubusercontent.com/64340763/116660146-3226ff00-a9c5-11eb-842f-53a0c1ea7bc3.png)
在stackblitz中的项目中使用
```
import { StepsGuideComponent } from "ng-devui/steps-guide";
entryComponents: [StepsGuideComponent]，
```
不需要在组件中添加~

**Comment by ZOUJIELynn** [comment]
> > > https://update.angular.io/?l=3&v=9.0-11.0
> > > Angular升级指南中有提到IVY与运行时不再需要entryComponents，我们升级后做了测试，请问下是组件有什么表现异常么
> > 
> > 
> > @ZOUJIELynn stackblitz 测试中, 如果没有 `entryComponents`, 会出现以下错误,
> > ![image](https://user-images.githubusercontent.com/64340763/116660146-3226ff00-a9c5-11eb-842f-53a0c1ea7bc3.png)
> > 在stackblitz中的项目中使用
> 
> ```
> import { StepsGuideComponent } from "ng-devui/steps-guide";
> entryComponents: [StepsGuideComponent]，
> ```
> 
> 不需要在组件中添加~
https://stackblitz.com/edit/ng-devui-11-qizuwf?file=src/app/app.module.ts

**Comment by Xie-Jay** [comment]
> > > https://update.angular.io/?l=3&v=9.0-11.0
> > > Angular升级指南中有提到IVY与运行时不再需要entryComponents，我们升级后做了测试，请问下是组件有什么表现异常么
> > 
> > 
> > @ZOUJIELynn stackblitz 测试中, 如果没有 `entryComponents`, 会出现以下错误,
> > ![image](https://user-images.githubusercontent.com/64340763/116660146-3226ff00-a9c5-11eb-842f-53a0c1ea7bc3.png)
> 
> stackblitz中angular的版本号是^11.0.0么

@ZOUJIELynn 是^11.0.0, 测试应该是 stackblitz 本身的问题, 我显示开启lvy就会报错, stackblitz/core#1364
