### ISSUE TITLE
如何覆盖组件的部分样式

### ISSUE THREAD

**Issue by LstHeart** [DevCloudFE/ng-devui#122]
在使用 DevUI 的 <d-rate></d-rate> 组件时，只读模式下, cursor 会被设置为 not-allowed，但我希望能更改 cursor 样式 ，尝试重写样式进行覆盖，却发现覆盖不了，请问如何去覆盖 DevUI 的部分样式？ 或者能否给 <d-rate></d-rate> 提供修改 cursor 样式的 API？

**Comment by wangyaju** [comment]
两种方式：
1. 全局样式覆盖，比如样式定义在入口的styles.(scss|less|css)文件中
2. 组件内覆盖子组件样式，使用`::ng-deep  .some-class` 来覆盖

@LstHeart

**Comment by LstHeart** [comment]
> 两种方式：
> 
> 1. 全局样式覆盖，比如样式定义在入口的styles.(scss|less|css)文件中
> 2. 组件内覆盖子组件样式，使用`::ng-deep  .some-class` 来覆盖
> 
> @LstHeart ,建议提供一个在线链接，具体看哪个组件

我之前看的是 rate 组件：https://devui.design/components/zh-cn/rate/demo ；
谢谢解答，目前我通过 ::ng-deep 的方式覆盖样式成功了，再次感谢！
