### ISSUE TITLE
导航菜单单独作为一个组件,而不是混合在手风琴示例里

### ISSUE THREAD

**Issue by xiejay97** [DevCloudFE/ng-devui#128]
找半天导航菜单没看到, 最后发现手风琴示例提供的是导航菜单
![image](https://user-images.githubusercontent.com/64340763/126584617-fcdadf87-3657-44e4-833b-96dc2e2af578.png)

**Comment by ZOUJIELynn** [comment]
> 找半天导航菜单没看到, 最后发现手风琴示例提供的是导航菜单 ![image](https://user-images.githubusercontent.com/64340763/126584617-fcdadf87-3657-44e4-833b-96dc2e2af578.png)

导航菜单正在内部测试，近两个版本会测试发出~

**Comment by Simplelegant** [comment]
内部正在重新设计demo 和 api展示形式,敬请期待~

**Comment by Simplelegant** [comment]
> > 内部正在重新设计demo 和 api展示形式,敬请期待~
> 
> 还接受pr吗？我想单独加一个menu组件

欢迎贡献，组件的API、交互等方案可以在此issue中讨论

**Comment by lycHub** [comment]
**你好，ng test 的时候 我这行代码通不过，不知道怎么解决，我没写过测试不太了解** 

![image](https://github.com/DevCloudFE/ng-devui/assets/29920553/9a8dbb53-e8e2-4386-be26-ea203b9649a3)

**Comment by lycHub** [comment]
menu组件我开发完了，不知道后面流程是？直接提pr吗？

**Comment by Simplelegant** [comment]
> menu组件我开发完了，不知道后面流程是？直接提pr吗？

 感谢贡献，我们会尽快对PR进行一次检视
