### ISSUE TITLE
Warning: D:\Seed\angular-seed\node_modules\ng-devui\__ivy_ngcc__\fesm2015\ng-devui-utils.js depends on 'date-fns/parse'. CommonJS or AMD dependencies can cause optimization bailouts.

### ISSUE THREAD

**Issue by qq1209974887** [DevCloudFE/ng-devui#129]
**Describe the bug**
引入ng-devui成功之后，启动基本正常，但是在命令行出现了警告：
```
Warning: D:\Seed\angular-seed\node_modules\ng-devui\__ivy_ngcc__\fesm2015\ng-devui-utils.js depends on 'date-fns/parse'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

**To Reproduce**
1. 创建angular项目
2. 引入ng-devui库并验证引入成功
3. 启动项目，查看命令行。

**Expected behavior**
预期无任何Warning警告，问题不大，但有潜在的风险存在，需要解决该问题以防止对生产项目造成潜在的有可能的影响和损失。

**Screenshots**
![image](https://user-images.githubusercontent.com/18743063/126904242-387e7e32-89d0-4daf-b485-c022f424493e.png)
![image](https://user-images.githubusercontent.com/18743063/126904217-8b49adeb-41f0-45b6-8f49-edacd0d9ec7b.png)

**environments (please complete the following information):**
 - Chrome Version [e.g. 91.0.4472.124]
 - Node [e.g. 14.17.0]
 - Angular-CLI [e.g. 11.0.9]
 - Angular [e.g. 11.0.7]

**Additional context**
问题已经描述完毕，无上下文可供参考。

**Comment by xiejay97** [comment]
`angular.json` 的 `allowedCommonJsDependencies` 项添加 `date-fns`

**Comment by wangyaju** [comment]
参考 @xiejay97 的解答
