### ISSUE TITLE
数字输入框粘贴进数字出现重复

### ISSUE THREAD

**Issue by ChenDvorak** [DevCloudFE/ng-devui#131]
数字输入框的组件，粘贴进数字会出现重复的数字，例如：粘贴 1 进数字框，会出现 11
附上代码地址：
https://stackblitz.com/edit/ng-devui-11-mlbd1u?file=src/app/app.component.html

粘贴前：
![1627436144(1)](https://user-images.githubusercontent.com/50647468/127249582-3de04409-5739-4151-a01a-85b94ec1e596.png)
粘贴数字 1 后：
![image](https://user-images.githubusercontent.com/50647468/127249604-0214a591-032d-42db-9e79-8514b0f558e0.png)

**environments (please complete the following information):**
 - Browser [e.g. chrome 80, safari]
 - component version [e.g. ^11.0.0]
 - angular framework version [e.g. 11.1.0]

**Comment by ZOUJIELynn** [comment]
12.1.0版本已解决~
