### ISSUE TITLE
希望集成可拖拽工作台或面板

### ISSUE THREAD

**Issue by Old-ear** [DevCloudFE/ng-devui#139]
之前看到华为云个人工作台有类似 https://github.com/tiberiuzuld/angular-gridster2 的个人工作面板
期待加入！

**Comment by ZOUJIELynn** [comment]
目前dashboard正在内部孵化中，近期会推出，敬请期待~

**Comment by kagol** [comment]
@Old-ear 12.2.0版本已提供该组件：Dashboard
