### ISSUE TITLE
[DataTable] 官网表格样式demo style 和 size 没有效果

### ISSUE THREAD

**Issue by ivestszheng** [DevCloudFE/ng-devui#153]
**描述**
官网表格样式demo style 和 size 没有效果

**浏览器**
 - 谷歌
 - 火狐
 - Edge

![官网 DataTable 截图](https://user-images.githubusercontent.com/70649502/138575933-3aaf129f-f0ee-462b-b2b3-4f9d46aeb67d.png)

**Comment by kagol** [comment]
@ivestszheng 新版本已解决
