### ISSUE TITLE
部分模块未考虑到浏览器兼容问题

### ISSUE THREAD

**Issue by ZhaoHongzcyh** [DevCloudFE/ng-devui#17]
例如：/devui/modal/movable.directive.ts
文件中的event.clientY以及event.clientX 是没办法保证一定能够得到期望值

**Comment by AnonymousArthur** [comment]
能不能详细讲讲，展开一些，举些例子？

**Comment by wangyaju** [comment]
@ZhaoHongzcyh ，好的，感谢提出建议，下个版本增加对应的兼容代码。

**Comment by wangyaju** [comment]
经过几个版本确认，目前组件涉及到的场景不存在兼容问题，issue关闭
