### ISSUE TITLE
documentation page can not open right.

### ISSUE THREAD

**Issue by ZQ-jhon** [DevCloudFE/ng-devui#18]
recurrent link: [recurrent link](https://devui.design/components/get-start)

![image](https://user-images.githubusercontent.com/26297704/77755718-c7d8b800-7068-11ea-9725-35186d602196.png)

**Comment by wangyaju** [comment]
@ZQ-jhon 抱歉，影响到你的体验，已经恢复。十分感谢帮我们指出问题。
