### ISSUE TITLE
[建议] kit中默认的style最好全部都带有自己的作用域或前缀

### ISSUE THREAD

**Issue by Zhengkaki** [DevCloudFE/ng-devui#182]
在angular.json中引入ng-devui/devui.min.css会破坏掉同命名的样式。
例如：
自身项目中我采用了grid布局，定义了一个style .grid {display: grid} 而DevUI中同样定义了一个.grid{letter-spacing:-.31em;word-spacing:-.43em}
这导致了我不得不去担忧DevUI其他样式是否会对我产生同样的问题。
我相信在DevUI中采用.devui-grid会是一个不错的做法。

**Comment by yannoc** [comment]
为什么这么好的建议没人理呐，总是回复一些练手项目问题 @kagol
