### ISSUE TITLE
Transfer 穿梭框组件Bug

### ISSUE THREAD

**Issue by OylDeGit** [DevCloudFE/ng-devui#185]
![image](https://user-images.githubusercontent.com/35057287/154622182-d7263115-4273-42f3-bc24-de31c040340f.png)
![image](https://user-images.githubusercontent.com/35057287/154622241-cc50f969-5a9d-44f1-804f-d4c887bb5a2b.png)
上张图点击以后，其中一项并未穿梭到目标数据源
![image](https://user-images.githubusercontent.com/35057287/154622329-c6c719db-8f40-441c-b927-10ef3f880b66.png)
![image](https://user-images.githubusercontent.com/35057287/154622401-178c671f-cac1-495d-b78d-6cd1e60c65a6.png)

实现代码:
![image](https://user-images.githubusercontent.com/35057287/154622432-4c85d3a5-b00a-471e-b2a2-c80b620ef7ff.png)
![image](https://user-images.githubusercontent.com/35057287/154622445-270bb9f5-c56e-4b86-a5c0-5b591d609ac5.png)

**Comment by kagol** [comment]
@OylDeGit 我尝试了下在demo里面未复现该问题：
[https://devui.design/components/zh-cn/transfer/demo#transfer-demo-base](https://devui.design/components/zh-cn/transfer/demo#transfer-demo-base)，可否在以下链接写下具体的复现demo呢？

[https://stackblitz.com/edit/ng-devui-12](https://stackblitz.com/edit/ng-devui-12)

**Comment by OylDeGit** [comment]
很奇怪，一样的代码，在这里stackblitz并未复现，但是我在Devui Admin示例项目里面测试又复现了

**Comment by OylDeGit** [comment]
您可以在Devui Admin示例项目中尝试一下

**Comment by kagol** [comment]
> 您可以在Devui Admin示例项目中尝试一下

好的，我也去DevUI Admin中试试看

**Comment by ricenoddle** [comment]
我在 Admin 中也没有复现，都是正常的，能麻烦反馈下你组件库版本，Admin 版本吗，讲道理 Admin 中没有什么特殊处理，不会出现这种情况的

**Comment by OylDeGit** [comment]
好吧， ng-devui-admin:   "version": "2.0.0",   "ng-devui": "^12.0.0",

**Comment by ricenoddle** [comment]
> 

我在本地用一样的版本试过了，我这边是正常的

**Comment by OylDeGit** [comment]
我就是拉的admin的代码，在上面加的，其他的没动，可以访问我这个链接看一下有无错误的地方https://oylxy.com/test.html

**Comment by ricenoddle** [comment]
> 我就是拉的admin的代码，在上面加的，其他的没动，可以访问我这个链接看一下有无错误的地方https://oylxy.com/test.html

看起来没有问题，在我这边确实没有复现，可以再检查下你本地的环境和代码
