### ISSUE TITLE
Cannot read properties of undefined (reading 'add')

### ISSUE THREAD

**Issue by bdatacloud-liushanshan** [DevCloudFE/ng-devui#186]
拖拽组件当鼠标按下去就会出现这个错误 Cannot read properties of undefined (reading 'add')
下面是错误堆栈
![image](https://user-images.githubusercontent.com/92718549/155290291-6e2a8654-8e32-4161-9b5d-7e7ef73b9b9f.png)

[版本]
^13.0.0

**Comment by ricenoddle** [comment]
麻烦可以提供一下复现代码吗谢谢

**Comment by zengyun261** [comment]
> 

官方文档中的DataTable行拖拽的代码就可以复现

**Comment by zengyun261** [comment]
@ricenoddle

**Comment by zengyun261** [comment]
> 我在行拖拽的demo里没有复现呢

跟rxjs版本有关, Subscription.add返回值发生了变化

**Comment by bdatacloud-liushanshan** [comment]
实在不好意思，这几天出差去了，忙没关注这个问题，感谢各位的反馈和帮助
