### ISSUE TITLE
强大的表格功能，竟然没有列配置功能？？？？强大在那里？

### ISSUE THREAD

**Issue by jy19950924** [DevCloudFE/ng-devui#206]
表格中列配置功能，现在使用还是听普遍的，但是devUI表格没有。主页还写强大的表格功能，这个强大在那里？

**Comment by foolmadao** [comment]
> 表格中列配置功能，现在使用还是听普遍的，但是devUI表格没有。主页还写强大的表格功能，这个强大在那里？

数据驱动的表格，你改变数据不就是列配置了吗，如果写一个样式交互都固定的列配置参数，那很难覆盖不同的交互场景。

你是不是需要组件库添加一个demo来演示下怎么写呢
