### ISSUE TITLE
后期会增加layout相关的功能吗？这个后台应用居多吧，有layout会方便很多。

### ISSUE THREAD

**Issue by ttnkh21** [DevCloudFE/ng-devui#21]
另外，打包后的体积有点大哦，空项目，只引入依赖devui，什么都没写，打包后的体积就有30多M哦

**Comment by wangyaju** [comment]
1. layout会增加的
@ttnkh21 体积的问题可以截个图吗

**Comment by ttnkh21** [comment]
![1585699198(1)](https://user-images.githubusercontent.com/23454757/78085896-ef27e000-73ee-11ea-9ab5-8fb0143611ed.jpg)
![1585699313(1)](https://user-images.githubusercontent.com/23454757/78086065-69f0fb00-73ef-11ea-8131-8d071107582b.jpg)
去掉map文件后，也有18M，这是配置了sourcemap嘛?
我的工程没有开启啊？
![1585699648(1)](https://user-images.githubusercontent.com/23454757/78086236-eb488d80-73ef-11ea-9466-40f4470698a0.jpg)

**Comment by wangyaju** [comment]
@ttnkh21 
1. sourceMap在serve模式下是默认开启的，方便调试定位，这个体积说明不了问题
2. 你现在展示的是没有经过prod配置优化的  加一下构建参数  ng  build --prod
3. 组件也支持按需引入   比如 import { ButtonModule } from 'ng-devui/button';

此issues关闭，有问题可以再开一个新的反馈，感谢。
