### ISSUE TITLE
new LoadingService() 如何手动new出来一个，参数怎么填写

### ISSUE THREAD

**Issue by izilongwan** [DevCloudFE/ng-devui#210]
new LoadingService() 如何手动new出来一个，参数怎么填写

我想手动new出来，但是参数不知道怎么写，这个参数好像有点。。。
还有就是open的参数loadingTemplateRef在这个方法里怎么配置ref

<img width="737" alt="image" src="https://user-images.githubusercontent.com/48234072/160286237-5bd0c609-18e4-4d6d-a2e3-b07aa1bc710c.png">

**Comment by izilongwan** [comment]
还有就是open的参数loadingTemplateRef在这个方法里怎么配置ref

**Comment by ricenoddle** [comment]
你这个要求好奇怪，为什么要去new 一个，直接注入就可以使用了
ref 你写个模板，获取到那个模板就可以传进了

**Comment by izilongwan** [comment]
> 你这个要求好奇怪，为什么要去new 一个，直接注入就可以使用了 ref 你写个模板，获取到那个模板就可以传进了

准备做装饰器用啊，不支持吗
