### ISSUE TITLE
【NavSprite】demo少了一个精灵用法

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/ng-devui#215]
复现链接：
[https://devui.design/components/zh-cn/nav-sprite/demo#basic](https://devui.design/components/zh-cn/nav-sprite/demo#basic)

![image](https://user-images.githubusercontent.com/9566362/162903502-1db54afd-f14e-42d5-95a4-98290fade72f.png)

**Comment by Simplelegant** [comment]
网站已更新，精灵用法demo未外放快速前往跳转已删除
