### ISSUE TITLE
DropDown 下拉菜单 手动控制下拉问题

### ISSUE THREAD

**Issue by ModelBoxDENG** [DevCloudFE/ng-devui#217]
在官网上, "通过设置isOpen控制下拉"的例子中,如果打开下拉菜单,再点击空白处,需要点两次按钮才能再次打开下拉菜单.

希望可以给一个点一次就能打开下拉菜单的例子

可以通过
onToggle(event) {
    if (this.isOpen != event) {
      this.isOpen = event;
    }
  }
来暂时解决这个问题

**Comment by kagol** [comment]
@ModelBoxDENG 感觉是一个bug，欢迎提交PR，加入devui贡献者队伍~
