### ISSUE TITLE
使用最新的组件库-报错

### ISSUE THREAD

**Issue by tang-love-1314** [DevCloudFE/ng-devui#22]
![360截图20200331205219411](https://user-images.githubusercontent.com/9675474/78028404-924a0c80-7391-11ea-9747-9598e5496f9d.jpg)

**Comment by wangyaju** [comment]
@tang-love-1314 麻烦反馈一下使用的ng版本 ，我们目前支持的版本是8.x

**Comment by wangyaju** [comment]
参考 #15 关闭此问题
