### ISSUE TITLE
【文档】官方文档错别字

### ISSUE THREAD

**Issue by JaylanChen** [DevCloudFE/ng-devui#221]
官方文档错别字
[设计模式-空白页](https://devui.design/design-cn/empty-page)

![image](https://user-images.githubusercontent.com/7055008/165297966-69e43b53-6236-47c0-89cb-7a4a3c97400a.png)

`借口` → `接口`

**Comment by kagol** [comment]
@JaylanChen 
Welcome PR! It's a fruit that can be picked. 😜😜
