### ISSUE TITLE
组件规范问题疑问

### ISSUE THREAD

**Issue by Sunzhuokai** [DevCloudFE/ng-devui#223]
拿简单的Button组件来说，市场上常见的设计规范，比如ant design，tdesign对于button设计三种尺寸高度分别为40px，32px，24px，对应的padding也都是15px，15px，7px，为何devui设计成32px，28px，24px。这种设计有何依据，背后有哪些用意呢？

**Comment by ZOUJIELynn** [comment]
> 拿简单的Button组件来说，市场上常见的设计规范，比如ant design，tdesign对于button设计三种尺寸高度分别为40px，32px，24px，对应的padding也都是15px，15px，7px，为何devui设计成32px，28px，24px。这种设计有何依据，背后有哪些用意呢？

组件库最开始服务的产品对于中等表单尺寸的要求是28px，padding的话常使用4的倍数，因为4的倍数在屏幕的各种缩放下能保证不会出现像素计算误差导致的不对齐等问题。
现在我们在做新版本的组件，高度的话也是切换成大家更习惯的32px，可以右上角切换主题至“无限”看看
