### ISSUE TITLE
dateFormat设置为“YYYY-MM-DD”时显示异常

### ISSUE THREAD

**Issue by hu-qi** [DevCloudFE/ng-devui#24]
DatePicker 日期选择器使用时将dateFormat设置为“YYYY-MM-DD”，获取到的时间显示为YYYY-04-DD。也就是说只有月份显示正常。
复现步骤和demo就不写了，我这边只需将dateFormated = 'YYYY-MM-DD';就会出现

ng-devui@8.0.0
windows 10
chrome 80.0.3987.149（正式版本） （64 位）

![image](https://user-images.githubusercontent.com/17986122/78234754-30f97900-750a-11ea-9580-7a5ad9189d63.png)

解决方案 dataFormat设为 yyyy-MM-dd就正常了

**Comment by ZOUJIELynn** [comment]
先使用dateFormat为y/MM/dd ，组件库下个版本会修复API的描述
