### ISSUE TITLE
13版本的Accordion组件autoOpenActiveMenu属性不生效

### ISSUE THREAD

**Issue by yequanrui** [DevCloudFE/ng-devui#240]
**Describe the bug**
在12之前的版本里，Accordion组件autoOpenActiveMenu属性不生效
在13版本里，属性就不生效了

**Screenshots**
![1](https://user-images.githubusercontent.com/26866409/176990150-082714ff-6cfb-4bc6-b67c-a26fd22efcda.gif)
![2](https://user-images.githubusercontent.com/26866409/176990100-7bb9f584-9179-49d8-a965-2f16ae6ca96c.gif)

**environments (please complete the following information):**
 - Browser Edge 103.0.1264.37
 - component version 13.2.0
 - angular framework version 13.2.7

**Comment by Simplelegant** [comment]
感谢提问，已在修复中
