### ISSUE TITLE
谁拯救小白

### ISSUE THREAD

**Issue by bouyeijiang** [DevCloudFE/ng-devui#242]
按官网操作添加好页面为什么点击菜单没有切换页面

**Comment by ZOUJIELynn** [comment]
> 按官网操作添加好页面为什么点击菜单没有切换页面

具体是参考的哪个文档，要实现什么功能呢

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的

**Comment by bouyeijiang** [comment]
就是在ng-devui-admin基础上加一个菜单页面，点击页面菜单

**Comment by Simplelegant** [comment]
你好，请在ng-devui-admin区求助 https://github.com/DevCloudFE/ng-devui-admin/issues

**Comment by bouyeijiang** [comment]
谢谢您的来信！我会及时查阅的
