### ISSUE TITLE
table 如何加个表尾

### ISSUE THREAD

**Issue by zsgee** [DevCloudFE/ng-devui#243]
固定在表格下面，充当合计表格的数据

**Comment by foolmadao** [comment]
都是数据驱动的，最下面加一行数据就可以

如果你想要的是像列固定一样的行固定功能话组件现在还不支持，你只能通过渲染两个表格间接实现

**Comment by zsgee** [comment]
试过加一行,是的固定行,那就只能两个表格左右滚动互相控制.

**Comment by foolmadao** [comment]
> 试过加一行,是的固定行,那就只能两个表格左右滚动互相控制.
还有横向滚动的话，你可以这样，用模板模式给最后一行加一个class，然后穿透覆盖一下行样式，position：sticky，bottom：0

**Comment by kagol** [comment]
@foolmadao 表尾感觉是很常见的需求，可以考虑以一种用户友好的方式进行支持

**Comment by zsgee** [comment]
> > 试过加一行,是的固定行,那就只能两个表格左右滚动互相控制.
> 
> 还有横向滚动的话，你可以这样，用模板模式给最后一行加一个class，然后穿透覆盖一下行样式，position：sticky，bottom：0


这种方式可以,之前试过更改行的位置,会变形
