### ISSUE TITLE
dToolTip does not work on d-tab elements

### ISSUE THREAD

**Issue by kwongtn** [DevCloudFE/ng-devui#247]
**Describe the bug**
dToolTip does not work on d-tab elements. Followed guide as described [here](https://devui.design/components/zh-cn/tooltip/api) but no tooltip appears.

**To Reproduce**
Do the following code.
```html
<d-tabs type="pills" size="lg" [(activeTab)]="tabActiveId" (activeTabChange)="activeTabChange($event)" 
[scrollMode]="tabItems.length > 5">
    <d-tab *ngFor="let item of tabItems" [id]="item.id">
        <ng-template dTabTitle dTooltip [content]="item.detail" [position]="'bottom'">
            {{ item.detail }}
        </ng-template>
    </d-tab>
</d-tabs>

```

**Expected behavior**
Upon hovering on the tab element, tooltip should appear.

**environments (please complete the following information):**
 - Chrome 103.0.5060.114
 - NgDevUI 13.3.0
 - Angular 13.3.11

**Comment by Simplelegant** [comment]
Do not use the dTooltip instruction on the ng-template. It is recommended that you use the dTooltip instruction in a layer outside {{ item.detail }} ~

```
<d-tabs [(activeTab)]="tabActiveId">
    <d-tab *ngFor="let item of tabItems" [id]="item.id">
      <ng-template dTabTitle>
        <div dTooltip [content]="item.detail">{{ item.detail }}</div>
      </ng-template>
    </d-tab>
  </d-tabs>
```

**Comment by kwongtn** [comment]
@Simplelegant it worked! Thank you so much 😁

Closing this issue
