### ISSUE TITLE
首页跳转地址错误

### ISSUE THREAD

**Issue by jack1ripper** [DevCloudFE/ng-devui#248]
**首页链接地址访问如图404**

![image](https://user-images.githubusercontent.com/32865628/179739494-b097a2b5-9912-428c-b004-f769ba2436b5.png)

**Comment by Simplelegant** [comment]
感谢建议，我们下版本修复链接地址
你可在此处查看主题切换器 https://github.com/DevCloudFE/ng-devui/tree/master/devui-commons/src/header/theme-picker

**Comment by Simplelegant** [comment]
问题已修复，欢迎访问查看
