### ISSUE TITLE
全屏组件d-fullscreen整死使用不了

### ISSUE THREAD

**Issue by duoduoObama** [DevCloudFE/ng-devui#25]
8.0环境和9.0环境都试了都不行，
问题1：看了dto文件是不是没导出到devui.module.d.ts
问题2：官网的demo是可以的，我到本地环境就报错：如下图
![image](https://user-images.githubusercontent.com/30836806/78767436-2ed96380-79bd-11ea-970e-0e4214dac753.png)
发誓，我公共依赖中引用了DevUIModule的，我用stackblitz和新建的项目不管是8.0和9.0环境都有这个报错，是我引用方式不对么，求大佬支招，或者给个stackblitz能用的demo，感激不尽，喜极而泣

**Comment by duoduoObama** [comment]
小声逼逼：还有就是有个建议，官网demo希望能像其它物料组件每个demo都能引用到stackblitz，直接可以debug

**Comment by qull** [comment]
可以单独引用这个组件

**Comment by ZOUJIELynn** [comment]
全屏组件暂未在DevUIModule导出，采用 ‘import { FullscreenModule } from '@avenueui/ng-devui/fullscreen';’ 的方式先导入使用

**Comment by ZOUJIELynn** [comment]
Demo链接到stackblitz or codepen之类的在线IDE我们会考虑优化~

**Comment by duoduoObama** [comment]
感谢大佬们刚刚使用了单独这个方法导出，就是没生效，刚重启start用这个单独导入就可以，自己使用起来太急躁了，感谢了，华为真太高效了，先来个彩虹屁，哈哈哈
