### ISSUE TITLE
[Docs] Icon API Section gives incorrect link to icon library

### ISSUE THREAD

**Issue by kwongtn** [DevCloudFE/ng-devui#253]
Refer the following page: https://devui.design/components/zh-cn/icon/api

![image](https://user-images.githubusercontent.com/5886584/183230178-14b90f4d-5e0e-47a3-a752-a6871e0f28d3.png)

The link there displays the following dead link
https://devui.design/components/zh-cn/icon/api

Which now should be: https://devui.design/icon/ruleResource

**Comment by Simplelegant** [comment]
Thanks for the advice, the problem has been fixed.
