### ISSUE TITLE
Cannot read properties of undefined (reading 'sourceRoot')

### ISSUE THREAD

**Issue by jipf2016** [DevCloudFE/ng-devui#255]
ng add ng-devui-admin
Skipping installation: Package already installed
? Please choose the default language you want to use:  简体中文 (zh-ch)
? Would you like to add lint files for your project? (default: Y) No
? Would you like to add mock module? (default: Y) No
? Would you like to add i18n? (default: Y) No

get

Cannot read properties of undefined (reading 'sourceRoot')

**Comment by foticc** [comment]
在 angular.json 中加入`"defaultProject": "your-projectname"`,新版本里面这个属性已经过时了
