### ISSUE TITLE
🐛 [Bug]: 表格中白色遮罩的问题

### ISSUE THREAD

**Issue by eggxu** [DevCloudFE/ng-devui#272]
### Version

14.0.0

### Angular Version

14.0.0

### Link to minimal reproduction

https://github.com/DevCloudFE/ng-devui/tree/master/devui/data-table/demo

### Step to reproduce

https://devui.design/components/zh-cn/datatable/demo
表格交互那个demo，横向滚动条拖动，然后将鼠标移出，就能看到，纵向的好像也有bug。

### What is expected

白色遮罩一直处于表格的末端，不会跟随滚动条的拖动改变位置，拖动到末端时消失

### What is actually happening

白色遮罩跟随滚动条的拖动而移动，导致遮住了表格里面的内容

**Comment by Simplelegant** [comment]
能否截个图呢，你说的白色遮罩是不是表格的阴影

**Comment by eggxu** [comment]
![BUG](https://user-images.githubusercontent.com/105786186/197925636-d9e94e5c-36a3-4583-b965-98580ef73689.png)

**Comment by Simplelegant** [comment]
问题已收到，我们尽快修复，麻烦留下浏览器版本号

**Comment by eggxu** [comment]
![edge-v](https://user-images.githubusercontent.com/105786186/198472076-69b214b1-aa8d-4097-b694-1018f29dc3f6.png)
