### ISSUE TITLE
🐛 [Bug]: DatePickerPro 日期选择器

### ISSUE THREAD

**Issue by zsgee** [DevCloudFE/ng-devui#277]
### Version

14.0.0

### Angular Version

14.2.1

### Link to minimal reproduction

DatePickerPro打开官网多日期选择器浮层,调整浏览器大小,在一个特定的值就会把日期的浮沉空白.只有周几的标题
![1666860698570](https://user-images.githubusercontent.com/95073924/198238947-133677cc-8790-4f88-96f6-225a07ba7d0a.jpg)

### Step to reproduce

打开DatePickerPro,调整浏览器宽度,在某个值中,再次打开,空白,没办法选择日期

**Comment by Simplelegant** [comment]
可以更加细化描述下复现路径及操作环境(ex. 浏览器版本)吗，在demo上没有复现出

**Comment by zsgee** [comment]
是更新了吗?14.1.0没有问题了,我的是Mac

**Comment by Simplelegant** [comment]
你好，组件最近也有更新，我们在mac上试了没有发现类似的问题
