### ISSUE TITLE
🐛 [Bug]: 全局样式不生效

### ISSUE THREAD

**Issue by sixinyiyu** [DevCloudFE/ng-devui#280]
### Version

14.1.0

### Angular Version

14.2.0

### Link to minimal reproduction

```
<d-row [dJustify]="'center'">
  <d-col [dSpan]="6">col-6</d-col>
  <d-col [dSpan]="6">col-6</d-col>
  <d-col [dSpan]="6">col-6</d-col>
</d-row>
```

### Step to reproduce

全局style.css 已导入```@import '~@devui-design/icons/icomoon/devui-icon.css'```

angular.json 也

···
 "styles": [
              "src/styles.css",
              "node_modules/ng-devui/devui.min.css"
            ],
···

### What is expected

![image](https://user-images.githubusercontent.com/3435446/201474651-13f5dbb2-83e8-4936-8d40-f81b39ae2f0c.png)

### What is actually happening

没有样式

**Comment by Simplelegant** [comment]
你好，需要在在全局样式中，引入：

`@import '~ng-devui/devui-layout.css';`

**Comment by bmbper** [comment]
> 

我引入时报：
./src/styles.scss - Error: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Can't resolve '~ng-devui/devui-layout.css' in '/Users/zgk/Code/10prod/bmb/bmbp_admin/ng-admin/src'

./src/styles.scss?ngGlobalStyle - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
HookWebpackError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Can't find stylesheet to import.
  ╷
3 │ @import "ng-devui/";
  │         ^^^^^^^^^^^
  ╵
  src/styles.scss 3:9  root stylesheet
