### ISSUE TITLE
🐛 [Bug]:  add devui admin 在install 阶段报错

### ISSUE THREAD

**Issue by hay313955795** [DevCloudFE/ng-devui#291]
### Version

latest

### Angular Version

 15.0.3

### Link to minimal reproduction

1

### Step to reproduce

# npm resolution error report

While resolving: tally@0.0.0
Found: @angular/animations@15.0.3
node_modules/@angular/animations
  @angular/animations@"^15.0.0" from the root project

Could not resolve dependency:
peer @angular/animations@"^13.0.0" from ng-devui@13.3.0
node_modules/ng-devui
  ng-devui@"^13.0.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

### What is expected

用了 ng add ng-devui-admin --legacy-peer-deps 这个命令也不能执行 安装的工作。是需要我修改什么地方吗？

### What is actually happening

1

### Any additional comments (optional)

1

**Comment by kwongtn** [comment]
@hay313955795 NgDevUI 目前只支持 Angular v14 或以下的版本

**Comment by hay313955795** [comment]
> DevUI 目前只支持 Angular v1
鹅鹅。原来如此。。

**Comment by kwongtn** [comment]
@kagol 提议 close issue
