### ISSUE TITLE
🐛 [Bug]: select弹出的下拉菜单选项的宽度失效

### ISSUE THREAD

**Issue by pony-xiaoma1** [DevCloudFE/ng-devui#292]
### Version

13.3.0

### Angular Version

13.1.2

### Link to minimal reproduction

1

### Step to reproduce

1

### What is expected

https://devui.design/13.3.0/components/zh-cn/select/demo#object-filter

<img width="588" alt="图片" src="https://user-images.githubusercontent.com/107979744/207933565-775d4479-7aec-4637-8957-f66d00e29bd2.png">

组件库html代码:
<d-select
        [options]="options2"
        [isSearch]="true"
        [filterKey]="'name'"
        [(ngModel)]="currentOption4"
        [placeholder]="'Search'"></d-select>

### What is actually happening

<img width="603" alt="图片" src="https://user-images.githubusercontent.com/107979744/207933758-db6dd02c-0b11-4c08-b97a-886d52dde581.png">

本人html代码：
<d-select [options]="type | keyvalue" [filterKey]="'value'" [isSearch]="true">
</d-select>

**Comment by Simplelegant** [comment]
demo中的效果需要开启扩展主题，建议参考[主题化使用指南](https://devui.design/components/zh-cn/theme-guide)或如下代码

1. 在main.ts中引入主题初始化服务和扩展风格4套主题
```
import { ThemeServiceInit } from 'ng-devui/theme';
import {
  infinityTheme,
  sweetTheme,
  provenceTheme,
  deepTheme,
} from 'ng-devui/theme-collection';
```
2. 在main.ts中初始化4套主题服务，并将默认主题置为无限主题
```
ThemeServiceInit({
  'infinity-theme': infinityTheme,
  'provence-theme': provenceTheme,
  'sweet-theme': sweetTheme,
  'deep-theme': deepTheme,
}, 'infinity-theme');
```
~~至此完成扩展风格主题的切换
