### ISSUE TITLE
🐛 [Bug]: Select 下拉选择框 文字回显错误

### ISSUE THREAD

**Issue by opxdo** [DevCloudFE/ng-devui#311]
### Version

ng-devui@15.1.0

### Angular Version

15.2.8

### Link to minimal reproduction

官网demo
https://devui.design/components/zh-cn/select/demo#object-filter

使用对象数组，通过filterKey配置对象显示字段。

### Step to reproduce

当 option 的value为 0, false, ""空字符串 时，文字回显不正确。应该显示为 "Option 1", 文本框显示成了 value 值
``` javascript 
options = [
    {
      name: 'Option 1',
//      value: 4,
      value: 0, 
    },
    {
      name: 'Option 2',
      value: 8,
    },
    {
      name: 'Option 3',
      value: 16,
    },
    {
      name: 'Option 4',
      value: 32,
    },
  ];
```

![select](https://user-images.githubusercontent.com/19682814/234240352-de6c66c9-69f3-4e7e-9531-a1f804028d74.png)

**Comment by Simplelegant** [comment]
问题已收到，我们近期修复
