### ISSUE TITLE
🐛 [Bug]: DataTable表格组件编辑单元格输入问题

### ISSUE THREAD

**Issue by cherking** [DevCloudFE/ng-devui#312]
### Version

latest

### Angular Version

latest

### Link to minimal reproduction

https://devui.design/components/zh-cn/datatable/demo#edit-cell

### Step to reproduce

我看例子里DataTable表格编辑单元格示例里，其他的列像Date of birth 和Age都是点击一次就可以编辑，但是第一个inpu输入框Last name却需要点两次才可以输入，我看配置项里配置了autofocus 是不是没有生效？

**Comment by foolmadao** [comment]
第一列使用了原生的input和原生属性autofocus，看起来这个原生行为嵌套在ng的组件中是无法生效的，我们后续会考虑下是否给textinput添加组件层的autofocus；
你们如果有需求可以先自己获取dom执行focus()事件来临时处理。
