### ISSUE TITLE
✨ [Feature]: 补全分类输入框等示例

### ISSUE THREAD

**Issue by cherking** [DevCloudFE/ng-devui#314]
### What problem does this feature solve

![image](https://user-images.githubusercontent.com/11309371/236977992-7632b05d-c155-40b3-8b4f-8611a987ab0b.png)
怎么找不到这些例子啊，是没有吗 能否补全一下

### What does the proposed API look like

补全组件

**Comment by Simplelegant** [comment]
感谢建议，已加入[2023 Idea Square](https://github.com/orgs/DevCloudFE/projects/2)
