### ISSUE TITLE
✨ [Feature]: update ng 16

### ISSUE THREAD

**Issue by Simplelegant** [DevCloudFE/ng-devui#317]
### What problem does this feature solve

升级DevUI到angular16版本，欢迎大家一起参与~

### What does the proposed API look like

升级DevUI到angular16版本，欢迎大家一起参与~

**Comment by kwongtn** [comment]
想请问 v16 更新是否有官方支持/进度？因为看到许多其他的 deps 都已有相对支持。
以个人项目来说的话，欠 ng-devui 的更新而已，谢谢。

**Comment by Simplelegant** [comment]
> 想请问 v16 更新是否有官方支持/进度？因为看到许多其他的 deps 都已有相对支持。 以个人项目来说的话，欠 ng-devui 的更新而已，谢谢。

已适配，即将发布~敬请期待
