### ISSUE TITLE
✨ [Feature]: Modal 模态弹窗添加全屏功能

### ISSUE THREAD

**Issue by xuxzh** [DevCloudFE/ng-devui#319]
### What problem does this feature solve

之前在ng-devui v9版本我们自己实现了模态框的全屏功能，如下图所示。请问在最新版的v15版本上有添加全屏功能的计划吗？或者我自己实现下，然后提个pr可以吗？
![image](https://github.com/DevCloudFE/ng-devui/assets/136676092/14339e34-67f5-4a99-a724-2b7bcf09e1f7)

![image](https://github.com/DevCloudFE/ng-devui/assets/136676092/0e030806-d220-426a-8043-a1c5cffda297)

### What does the proposed API look like

![image](https://github.com/DevCloudFE/ng-devui/assets/136676092/edd0ad33-e10d-45b7-a46c-16220da79107)
![image](https://github.com/DevCloudFE/ng-devui/assets/136676092/9460a708-2c25-42f2-a04e-24ad2ab4cb9b)
![image](https://github.com/DevCloudFE/ng-devui/assets/136676092/308b7985-9c3f-42fc-a79d-ca532a2f2048)

**Comment by Simplelegant** [comment]
欢迎提PR参与贡献~

**Comment by xuxzh** [comment]
已提PR，麻烦看下是否可行：https://github.com/DevCloudFE/ng-devui/pull/320

**Comment by Simplelegant** [comment]
> 已提PR，麻烦看下是否可行：#320

感谢贡献，我们看下代码~
