### ISSUE TITLE
🐛 [Bug]: 主题功能存在bug

### ISSUE THREAD

**Issue by zozero** [DevCloudFE/ng-devui#321]
### Version

latest

### Angular Version

15.2.0

### Link to minimal reproduction

当浏览器的`local Storage`中已经有字段`user-custom-theme`时`ThemeServiceInit`函数不起作用。
在某些特殊情况下`user-custom-theme`的值会是empty-theme。

解决方法之一，可以使用在浏览器中直接删除`local Storage`中的相应的字段，刷新后重新起作用。
解决方法之二，也可以在`main.ts`文件中添加`localStorage.removeItem("user-custom-theme");`，直接在开启项目时就移除掉一次该键，但在生产环境中不建议这样使用。

### Step to reproduce

这可能意味着一开始没有设置`ThemeServiceInit`函数启动浏览器后，设置`ThemeServiceInit`将不起作用。
当然当你再次修改`ThemeServiceInit`函数后运行编译也会不起作用。
主要是因为浏览器没有清除缓存。

**Comment by Simplelegant** [comment]
可以尝试如下步骤
1. main.ts中初始化主题
```
ThemeServiceInit({
  'infinity-theme': infinityTheme,
  'provence-theme': provenceTheme,
  'sweet-theme': sweetTheme,
  'deep-theme': deepTheme,
}, 'infinity-theme');
```

2. 项目公共组件处(ex. header中)调用如下方法，确保项目每次加载可调用到
window['devuiThemeService'].applyTheme(window['devuiThemes']['infinity-theme']);
