### ISSUE TITLE
✨ [Feature]: ng版本data-table组件在视图模式下负责呈现单元格内容的自定义组件

### ISSUE THREAD

**Issue by wujisui** [DevCloudFE/ng-devui#327]
### What problem does this feature solve

自己做第二次封装，比如在表格的操作栏加入一些button（用于编辑、删除、预览、查看当前行数据）、select、input等等一系列的表单元素，甚至一些用来显示当前行数据的一些状态tag的子组件，这些组件可以通过column配置传递到二次封装的data-table组件

### What does the proposed API look like

类似该插件 https://akveo.github.io/ng2-smart-table/#/documentation 里面的renderComponent

**Comment by Simplelegant** [comment]
这个想法很棒，欢迎参与贡献共建哦

**Comment by foolmadao** [comment]
column模式下，组件提供了d-cell模板，你可以自行封装想添加的内容
