### ISSUE TITLE
🐛 [Bug]: tabs中签入iframe的问题

### ISSUE THREAD

**Issue by 75910456** [DevCloudFE/ng-devui#342]
### Version

ng-devui@16.1.0

### Angular Version

16.2.12

### Link to minimal reproduction

    <d-tabs
      class="d-tabs"
      [type]="'wrapped'"
      [(activeTab)]="tabActiveId"
      [closeable]="true"
      [closeableIds]="closeableIds"
      (activeTabChange)="activeTabChange($event)"
    >
      <d-tab
        class="d-tab"
        *ngFor="let item of dynamicTabData"
        [id]="item.id"
        [title]="item.title"
      >
        <iframe class="iframe" src="https://xxxxxxxx/"></iframe>
      </d-tab>
    </d-tabs>

### Step to reproduce

d-tabs中放入iframe，每次tab切换后，iframe中的内容都被重新加载了，要如何使iframe不重新加载呢？

    <d-tabs
      class="d-tabs"
      [type]="'wrapped'"
      [(activeTab)]="tabActiveId"
      [closeable]="true"
      [closeableIds]="closeableIds"
      (activeTabChange)="activeTabChange($event)"
    >
      <d-tab
        class="d-tab"
        *ngFor="let item of dynamicTabData"
        [id]="item.id"
        [title]="item.title"
      >
        <iframe class="iframe" src="https://xxxxxxxx/"></iframe>
      </d-tab>
    </d-tabs>

**Comment by Simplelegant** [comment]
设置`isHidden=true`就不销毁content的dom了
