### ISSUE TITLE
✨ [Feature]: 请教一下，有没有办法可以在不同的页面来设置这个页面的主题，而不是整个项目的？

### ISSUE THREAD

**Issue by liqupanpan** [DevCloudFE/ng-devui#349]
### What problem does this feature solve

✨ [Feature]: 请教一下，有没有办法可以在不同的页面来设置这个页面的主题，而不是整个项目的？

### What does the proposed API look like

✨ [Feature]: 请教一下，有没有办法可以在不同的页面来设置这个页面的主题，而不是整个项目的？

**Comment by Simplelegant** [comment]
通过进入不同页面的时候切换主题应该可以实现
