### ISSUE TITLE
🐛 [Bug]: 表格列宽拖动代码可能存在问题

### ISSUE THREAD

**Issue by chester0424** [DevCloudFE/ng-devui#352]
### Version

1.7.1.0

### Angular Version

17.3.0

### Link to minimal reproduction

https://[github.com](https://github.com/DevCloudFE/ng-devui)/DevCloudFE/ng-devui/devui/data-table/table/head/th/th.component.ts

### Step to reproduce

devui/data-table/table/head/th/th.component.ts 中 onMousedown和onMouseup成对方法，
onMousedown 方法添加resize-overlay元素代码：   this.renderer2.appendChild(this.element.firstElementChild, this.resizeOverlay); 而在 onMouseup方法中删除元素diamante：    this.renderer2.removeChild(this.element, this.resizeOverlay); 

导致运行时报错 ERROR DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### Any additional comments (optional)

修改成：      this.renderer2.removeChild(this.element.firstElementChild, this.resizeOverlay); 
就正常了

**Comment by Simplelegant** [comment]
感谢贡献
