### ISSUE TITLE
是否有必要做组件库单元测试

### ISSUE THREAD

**Issue by oppoffice** [DevCloudFE/ng-devui#36]
如果组件库不做单元测试,后期维护如何保障应用不会出问题. 如: table, form, tree,date,...这些比较大型的组件. Angular 对 tslint的支持后期可能会过渡到 eslint上

**Comment by wangyaju** [comment]
@oppoffice 单元测试已经在写了，也欢迎参与共建

**Comment by zhangwellyear** [comment]
有必要，单元测试正在书写中
