### ISSUE TITLE
d-checkbox [label] 属性不能赋值中文

### ISSUE THREAD

**Issue by supermanqd** [DevCloudFE/ng-devui#42]
**Describe the bug**
<d-checkbox name="rememberme"     [label]="记住我"    ></d-checkbox>

typescript 编译报错

**To Reproduce**

**Expected behavior**

**Screenshots**

**environments (please complete the following information):**
 - Browser [e.g. chrome 80, safari]
 - component version [e.g. 8.0.0]
 - angular framework version [e.g. 8.0.0]

**Additional context**

**Comment by ZOUJIELynn** [comment]
[label]="'记住我'" 或 label="记住我", 试试这样写
