### ISSUE TITLE
发现TreeSelect 树形选择框组件疑似有问题(链接已更新)

### ISSUE THREAD

**Issue by 929496959** [DevCloudFE/ng-devui#48]
[疑似问题GIF](http://git.homeboy.cc:8888/xz.gif)已更新

**Comment by 929496959** [comment]
![image](http://chuantu.xyz/t6/739/1593863059x992248267.gif)

**Comment by wangyaju** [comment]
@929496959 图片看不到，可以详细描述一下使用场景，附上截图

**Comment by 929496959** [comment]
![image](http://git.homeboy.cc:8888/xz.gif)

**Comment by ZOUJIELynn** [comment]
这个原因是我们对下拉框做了自适应方向，以及tree-select的z-index值高于header的z-index
