### ISSUE TITLE
图标库怎么使用

### ISSUE THREAD

**Issue by supermanqd** [DevCloudFE/ng-devui#49]
**Describe the bug**
按照说明 @devui-design/icons已安装，angular.json 中 "node_modules/ng-devui/devui.min.css" 已引用。但 icon 属性引用的字体图标不显示，也不报错。请问下应该怎么使用。
`<d-button icon="icon-add" bsStyle="primary">
      新建
</d-button>`

类似样例中这样。
样例：`<span  _ngcontent-rnn-c74="" class="devui-icon-fix icon icon-add clear-right-5 ng-star-inserted"></span>`
我的 `<span _ngcontent-sco-c66="" class="devui-icon-fix icon icon-add clear-right-5" ng-reflect-ng-class="[object Object]"></span>`
class 少了  ng-star-inserted。
**To Reproduce**

**Expected behavior**

**Screenshots**

**environments (please complete the following information):**
 - Browser [e.g. chrome 80, safari]
 - component version [e.g. 8.0.0]
 - angular framework version [e.g. 8.0.0]

**Additional context**

**Comment by ZOUJIELynn** [comment]
1. 在全局的样式表或angular.json的styles里引入 ‘@import '~@devui-design/icons/icomoon/devui-icon.css'’
2. 使用方式为在class中添加复制的图标：
例如<span class="icon icon-add-file"></span>

图标库引入方式我们会尽快在页面上补充~

**Comment by supermanqd** [comment]
> 
> 
>     1. 在全局的样式表或angular.json的styles里引入 ‘@import '~@devui-design/icons/icomoon/devui-icon.css'’
> 
>     2. 使用方式为在class中添加复制的图标：
>        例如`<span class="icon icon-add-file"></span>`
> 
> 
> 图标库引入方式我们会尽快在页面上补充~

谢谢，经测试，只要引入 @devui-design/icons/icomoon/devui-icon.css 就行， 使用时不需要增加 class
