### ISSUE TITLE
筛选框样式问题

### ISSUE THREAD

**Issue by DK-ccyfy** [DevCloudFE/ng-devui#51]
选择数量较少时候有样式问题
![image](https://user-images.githubusercontent.com/12626368/87401838-45f7a500-c5ed-11ea-8677-aee2a7cf4bb6.png)

应该表现样式为：
![image](https://user-images.githubusercontent.com/12626368/87402020-8820e680-c5ed-11ea-93b8-29101df5f737.png)

修改方式：在类‘devui-dropdown-menu‘ 或’ devui-dropdown-overlay’最小高度改为165左右即可，2个选项应该是最少的情况。
![image](https://user-images.githubusercontent.com/12626368/87402086-a1299780-c5ed-11ea-95e4-7a4ebb834a38.png)

**Comment by qull** [comment]
最小高度过大导致，后续版本优化一个恰当的高度
