### ISSUE TITLE
日期选择回调问题

### ISSUE THREAD

**Issue by DK-ccyfy** [DevCloudFE/ng-devui#52]
![image](https://user-images.githubusercontent.com/12626368/87528174-bff85e80-c6bf-11ea-9e39-5a3e0cdcccac.png)
当前只有回调selectedRangeChange()方法获取值改变，但是上图这种需要点击【确定】时候再取回调。

官方现在暂时给出的解决办法是：
![image](https://user-images.githubusercontent.com/12626368/87528402-0e0d6200-c6c0-11ea-8834-941772cf06aa.png)
reason为2的时候是点击的确定回调。

**Comment by ZOUJIELynn** [comment]
嗯嗯 这个问题我们会考虑优化回调事件的reason

**Comment by AnonymousArthur** [comment]
这个可以考虑加一个confirm event。
