### ISSUE TITLE
datatable设置[virtualScroll]="true"报错

### ISSUE THREAD

**Issue by supermanqd** [DevCloudFE/ng-devui#53]
datatable设置[virtualScroll]="true"后，console显示如下错误，并且不加载数据
ERROR TypeError: table.rows[0] is undefined
    buildFakeTable ng-devui-data-table.js:4650
    renderFixFakeTableEl ng-devui-data-table.js:4637
    ngOnChanges ng-devui-data-table.js:4381
    Angular 40
    RxJS 5
    Angular 9
core.js:6228:19

**Comment by qull** [comment]
> datatable设置[virtualScroll]="true"后，console显示如下错误，并且不加载数据
> ERROR TypeError: table.rows[0] is undefined
> buildFakeTable ng-devui-data-table.js:4650
> renderFixFakeTableEl ng-devui-data-table.js:4637
> ngOnChanges ng-devui-data-table.js:4381
> Angular 40
> RxJS 5
> Angular 9
> core.js:6228:19

代码贴一下，你是否在使用列拖拽的特性+虚拟滚动的特性？

**Comment by supermanqd** [comment]
> 6

`<d-data-table #datatable 
        [checkable]="true"
        dLoading
        [columnAdjustStrategy]="columnAdjustStrategy"
        [dataSource]="dataSource" 
        colDraggable="true" 
        colDropFreezeTo="1"        
        [hideColumn]="hideColumn"
        fixHeader="true"
        maxHeight="{{tableHeight}}px"
        (multiSortChange)="multiSortChange($event)"
        [onlyOneColumnSort]="false"
        (resize)="onResize($event)"
        (rowDBClick)="onRowDoubleClick($event)"
        [scrollable]="true"
        [showLoading]="showLoading"
        [showSortIcon]="true"
        [tableWidth]="'100%'" 
        [type]="'striped'"
        [virtualScroll]="true"
        >`

**Comment by supermanqd** [comment]
使用了列拖拽的特性+虚拟滚动的特性
