### ISSUE TITLE
Splitter “错乱”

### ISSUE THREAD

**Issue by Tatamethues** [DevCloudFE/ng-devui#54]
**Describe the bug**
测试用orientation=vertical，三个splitter-pan，每个都 [collapsible]="true"。
1. 多次点击不同的箭头，可能某一个区域就怎么也点不回来了。如图1，怎么也找不回来“下”了，两个箭头点上面的隐藏”上“，点下面的隐藏“中”。
2. 图二，[collapsible]="true" 每次只能设置一个，就是这么设计的么？如果是这样的话，问题1例的问题。。就很奇怪了。
```
    spliterTest = [
        {
            size: '30%',
            collapsed: false,
            text: '上',
            min: '5%',
        },
        {
            size: '30%',
            collapsed: true,
            text: '中',
            min: '5%',
        },
        {
            size: '40%',
            collapsed: true,
            text: '下',
            min: '5%',
        },
    ];

```
```
    <d-splitter style="height: 900px; border: 1px solid #e3e5e9;" orientation="vertical">
        <d-splitter-pane
            *ngFor="let pane of spliterTest"
            [size]="pane.size"
            [minSize]="pane.min"
            [collapsible]="true"
            [collapsed]="pane.collapsed"
        >
            <div class="pane-content">
                <h2>{{ pane.text }}</h2>
            </div>
        </d-splitter-pane>
    </d-splitter>
```
3.接问题2，无法拖拽。有时候拖拽过程中

**Expected behavior**
1. 可以隐藏多个
2. 最好能。。单个或者多个隐藏时候仍然可以正常拖拽

**Screenshots**
图1
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/34636866/88076559-cbaac000-cbac-11ea-865a-d972072455ce.png">
图2
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/34636866/88078485-1e857700-cbaf-11ea-94d7-a39efb65dc2c.png">

**Additional context**
辛苦了。。加油

**Comment by wangyaju** [comment]
@Tatamethues 
1. 所有面板都支持collapsible属性的话，非边缘面板，建议配合[collapseDirection]="'before'"属性使用，目前按钮隐藏设计是关闭时，隐藏相邻面板的按钮
2. 隐藏一个后者多个时，如果剩余的几个面板没有禁用resizable的话，是可以拖拽的

你可以基于https://stackblitz.com/edit/ng-devui-9 提供一个演示demo，方便我们分析
