### ISSUE TITLE
没有react vue版的计划吗？

### ISSUE THREAD

**Issue by cike8899** [DevCloudFE/ng-devui#56]
没有react vue版的计划吗？

**Comment by wangyaju** [comment]
@cike8899 短期内聚焦angular版本的打磨，后续会考虑

**Comment by Old-ear** [comment]
@cike8899 已经在出vue的了，估计今年就能见面

**Comment by ZOUJIELynn** [comment]
vue版本可以关注 https://gitee.com/devui/vue-devui

**Comment by kagol** [comment]
React DevUI我们的PMC成员已经在孵化了，可以关注下：https://github.com/xiejay97/react-devui
也欢迎参与共建~
@cike8899
