### ISSUE TITLE
DataTable error when enabled both "resizeable" and "fixHeader"

### ISSUE THREAD

**Issue by alexshar** [DevCloudFE/ng-devui#58]
**Describe the bug**
DataTable error when enabled both "resizeable" and "fixHeader"

**To Reproduce**

1. add <d-data-table>
2. set [resizeable] to true
3. set [fixHeader] to true
4. it is possible that there is a error message on Console. I am not clear the side effect because of this.

**Expected behavior**

**Screenshots**
this is the output from chrome
![2020-08-20 143952](https://user-images.githubusercontent.com/3507645/90725705-28f07900-e2f3-11ea-9a73-20632ff562d6.png)

**environments (please complete the following information):**
 - chrome 84
 - devui 9.1.0
 - angular framework version 10.0.2

**Additional context**
NONE

**Comment by qull** [comment]
This issue will be resolved in the next release
