### ISSUE TITLE
按钮设置禁用后，点击仍然可以触发click事件

### ISSUE THREAD

**Issue by jeremynancy** [DevCloudFE/ng-devui#60]
![image](https://user-images.githubusercontent.com/48818841/92063268-619d5180-edcd-11ea-8ec8-8d733f616dd1.png)
![image](https://user-images.githubusercontent.com/48818841/92063319-7f6ab680-edcd-11ea-94d5-d77c1292a19b.png)
![image](https://user-images.githubusercontent.com/48818841/92063378-98736780-edcd-11ea-9a87-a022e2a2c86a.png)

**Comment by wangyaju** [comment]
@jeremynancy 参考一下button api的事件描述，当前版本暂时不支持原生click，需要使用`btnClick`，原生click下个版本支持
