### ISSUE TITLE
表格报错

### ISSUE THREAD

**Issue by DK-ccyfy** [DevCloudFE/ng-devui#61]
![image](https://user-images.githubusercontent.com/12626368/92216776-5a5b6e00-eec9-11ea-9916-2558cd98c4db.png)
加了这个  [fixHeader]="true"会报以下错误
![image](https://user-images.githubusercontent.com/12626368/92216937-91ca1a80-eec9-11ea-9c32-3d3bc909c4bf.png)

原因应该同表格内容无关，因为都是最基础的，没有加任何多余的属性

**Comment by qull** [comment]
是否使用最新版本？

**Comment by wangyaju** [comment]
@DK-ccyfy  新版本我们验证没有此类问题，可以使用最新版本验证一下
