### ISSUE TITLE
Checboxgroup radioGroup 值缺少 valueKey. labelKey. 用于值和名称的获取

### ISSUE THREAD

**Issue by LBLen** [DevCloudFE/ng-devui#64]
**Describe the bug**

**To Reproduce**

**Expected behavior**

checkboxGroup 值 可以是这样
```
[
 {name: 'name1', value: 'value1', checked: false},
 {name: 'name2', value: 'value3', checked: false}
]
```
也可以这样, 当用到了 valueKey时, valueKey可以是字符串也可以是回调函数
[
'value1',
'value3',
]

**Screenshots**

**environments (please complete the following information):**
 - Browser [e.g. chrome 80, safari]
 - component version [e.g. 8.0.0]
 - angular framework version [e.g. 8.0.0]

**Additional context**

**Comment by wangyaju** [comment]
@LinBoLen 目前，对于对象形式的option，可以通过模板来实现lable的自定义显示，选中会把当前option都提供出来，方便处理
