### ISSUE TITLE
validate.type.d.ts:15:5 - error TS2411: Property 'id' of type 'string | undefined' is not assignable to string index type 'string | number | boolean | RegExp | ValidatorFn | DValidatorFn'.

### ISSUE THREAD

**Issue by smart817** [DevCloudFE/ng-devui#78]
空项目，加载DevUIModule后，编译的时候过不去，不知道别人有遇到没
Error: node_modules/ng-devui/form/validator-directive/validate.type.d.ts:15:5 - error TS2411: Property 'id' of type 'string | undefined' is not assignable to string index type 'string
| number | boolean | RegExp | ValidatorFn | DValidatorFn'.

15     id?: string;
       ~~
node_modules/ng-devui/form/validator-directive/validate.type.d.ts:16:5 - error TS2411: Property 'validator' of type 'ValidatorFn | DValidatorFn | undefined' is not assignable to string index type 'string | number | boolean | RegExp | ValidatorFn | DValidatorFn'.

16     validator?: DValidatorFn | ValidatorFn;

**Comment by GreatZPP** [comment]
#75

**Comment by wangyaju** [comment]
和问题  #77 重复，Angular11之后引入了严格模式， TS的checknull对optional参数会默认增加一个undefined类型，导致可选字段和索引字段一起使用时类型不匹配，采用11版本时，关闭严格模式就可以了，下个版本会解决。
