### ISSUE TITLE
有计划提供一个通用的后台模板吗

### ISSUE THREAD

**Issue by zjh599245299** [DevCloudFE/ng-devui#80]
有计划提供一个通用的后台模板吗

**Comment by zjh599245299** [comment]
风格很喜欢 api写的也很好  希望一直更新下去 增加更多的功能和组件

**Comment by GreatZPP** [comment]
对于后台模板已在新的一年重点规划内 感谢对于我们的肯定 DevUI演进也期待收到你更多的使用感受与建议

**Comment by GreatZPP** [comment]
将在 #37 中更新进度
