### ISSUE TITLE
ImagePreview 图片预览组件点击放大不显示图片

### ISSUE THREAD

**Issue by zzhangshuo** [DevCloudFE/ng-devui#82]
ImagePreview 图片预览组件点击放大不显示图片
正常点击图片放大后这样，官网例子
![image](https://user-images.githubusercontent.com/65998296/103860395-80eb1900-50f6-11eb-8412-8e8b9fa2c4bf.png)

![image](https://user-images.githubusercontent.com/65998296/103860297-65800e00-50f6-11eb-9773-3d620a573bfb.png)
然后就这样了
![image](https://user-images.githubusercontent.com/65998296/103860486-a9731300-50f6-11eb-83e9-9c8dfd237be2.png)

html代码
<div dImagePreview>
  <img src="http://cdsyyt.7766.org:8102/static/busimages/2020121003521474.png"  />
</div>

app.module.ts 部分相关代码
import { AppComponent } from './app.component';
import { DevUIModule } from 'ng-devui';

@NgModule({
  declarations: [
    AppComponent
  ],
  imports: [ 
    DevUIModule
  ],

**Comment by GreatZPP** [comment]
我们可能需要你的html代码部分代码进行问题识别，还有控制台报错信息

**Comment by zzhangshuo** [comment]
> 我们可能需要你的html代码部分代码进行问题识别，还有控制台报错信息

html关于图片预览组件的相关代码
<div dImagePreview>
  <img src="http://cdsyyt.7766.org:8102/static/busimages/2020121003521474.png"  />
</div>
关闭图片预览弹窗时控制台报以下错误
core.js:5967 ERROR TypeError: Cannot read property 'removeElementListener' of undefined
    at DImagePreviewComponent.ngOnDestroy (ng-devui-image-preview.js:209)
    at executeOnDestroys (core.js:7149)
    at cleanUpView (core.js:7062)
    at destroyViewTree (core.js:6888)
    at destroyLView (core.js:7040)
    at RootViewRef.destroy (core.js:22335)
    at ng-devui-modal.js:592
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:28269)

**Comment by zzhangshuo** [comment]
> 我们可能需要你的html代码部分代码进行问题识别，还有控制台报错信息

能给看一下嘛，谢谢

**Comment by GreatZPP** [comment]
html为你实际编写的html代码，并非是图片截图哈

**Comment by zzhangshuo** [comment]
> html为你实际编写的html代码，并非是图片截图哈
 
 html代码粘贴上来自动就变成图片了 因为有img标签
<div dImagePreview>
  <img src="图片地址"  />
</div>

**Comment by GreatZPP** [comment]
尝试使用markdown code包裹你的代码，防止渲染

**Comment by zzhangshuo** [comment]
> 尝试使用markdown code包裹你的代码，防止渲染
<code>
<div dImagePreview>
  <img src="http://cdsyyt.7766.org:8102/static/busimages/2020121003521474.png"  />
</div>
</code>

**Comment by zzhangshuo** [comment]
> markdown code包裹你的代码，防止渲染

<pre>
  <div dImagePreview>
    <img src="http://cdsyyt.7766.org:8102/static/busimages/2020121003521474.png"  />
  </div>
</pre>

**Comment by zzhangshuo** [comment]
> 尝试使用markdown code包裹你的代码，防止渲染
html相关代码，感谢
`<div dImagePreview>`
  `<img src="http://cdsyyt.7766.org:8102/static/busimages/2020121003521474.png"  />`
`</div>`

**Comment by GreatZPP** [comment]
经过测试 在页面中imagepreview可正常显示
与 @zzhangshuo 进一步查看后按照demo 可组件可正常使用
