### ISSUE TITLE
[官网]InputNumber组件的链接问题

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/ng-devui#88]
https://devui.design/components/zh-cn/input-number
此组件跳转之后会自动加上锚点，跳转到禁止输入态的demo：
https://devui.design/components/zh-cn/input-number/demo#number-disabled

**Comment by kagol** [comment]
最后一个demo有一个autoFocus导致的

**Comment by wangyaju** [comment]
@kagol 已修正
