### ISSUE TITLE
[官网]Accordion组件Demo文案错误

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/ng-devui#92]
复合层级那个Demo标题文案少了一个“开”字

复合层级和自动展
->
复合层级和自动展开

<img width="589" alt="图片" src="https://user-images.githubusercontent.com/9566362/108625261-e74cb080-7484-11eb-81bc-b6eb3644a888.png">

Demo链接：
https://devui.design/components/zh-cn/accordion/demo#compound-level-and-auto-expand

**Comment by wangyaju** [comment]
好的，下个版本修复
