### ISSUE TITLE
merge最新master代码之后无法通过静态检查，这个要如何解决呢？

### ISSUE THREAD

**Issue by kagol** [DevCloudFE/ng-devui#94]
merge最新master代码之后无法通过静态检查，这个要如何解决呢？

<img width="679" alt="图片" src="https://user-images.githubusercontent.com/9566362/109404674-37ef6c80-79a3-11eb-92a8-08898514bddd.png">

**Comment by kagol** [comment]
这个问题我看master分支本身就存在

**Comment by ZOUJIELynn** [comment]
> 这个问题我看master分支本身就存在

下个版本修复提交~
