### ISSUE TITLE
单选框组件数据绑定问题

### ISSUE THREAD

**Issue by ChenDvorak** [DevCloudFE/ng-devui#97]
我按照官方的教程使用单选框组件，点击切换选项的时候，在控制台里报了error，ERROR TypeError: _this.onChange is not a function，却绑定的[(ngModel)]不会改变。
附上代码：https://stackblitz.com/edit/ng-devui-11-jhsujf?file=src/app/app.component.html
我在 Edge 和 Chrome 中都试过，都是一样的问题。
入下图，value 绑定单选框选中的值，初始化为 11
![image](https://user-images.githubusercontent.com/50647468/111427428-12978800-8731-11eb-9a6a-0e8c204066f6.png)
此时点击到 22，绑定的值不会改变，并在控制台出现如下信息
![image](https://user-images.githubusercontent.com/50647468/111427306-e419ad00-8730-11eb-9fdc-33b18db5a38b.png)
是我操作不当吗

**Comment by Simplelegant** [comment]
您好，我看了代码ngModel的位置不合适，应该放在d-radio-group中，修改为如下图所示即可
![image](https://user-images.githubusercontent.com/7804989/111563863-b89bce80-87d3-11eb-9529-b0c4a46973c8.png)

**Comment by ChenDvorak** [comment]
多谢，是我使用不当。
